brocaar/chirpstack-application-server

.travis.yml, Makefile, README.md, docs/index.md
=> Improve Makefile

docs/content/install/requirements.md
A small comment for the Raspberry users on how to install psql-9.6.
=> How to install psql-9.6 for Raspberry Pi users

docs/content/integrate/data.md
The documentation was not updated when the rename was made in the code.
=> docs: Change nodeName to deviceName

ui/package-lock.json, ui/package.json, ui/src/stores/GatewayStore.js, ui/src/stores/NodeStore.js
This feature is implemented with [reconnecting-websocket](https://www.npmjs.com/package/reconnecting-websocket) library.
And this pull-request applies some tiny refactorings.
=> Support WebSocket reconnection for live frame logs

ui/src/components/DeviceProfileForm.js
fix label of ABP frequency of device configuration
=> fix frequency 860.1 to 868.1

docs/content/integrate/sending-receiving/mqtt.md
DevEUI->devEUI in Join notification
=> Fix typo in devEUI attribute

packaging/files/lora-app-server.init
fix logrotate processing by using a >> operator instead of >
ref brocaar/lora-app-server#277
=> fix logrotate processing 

docs/content/use/fuota.md
I was reading the documentation about Fuota and I came across with some typos. This PR aims to fixing them.
=> Fixing typo on Fuota section.

ui/src/components/AESKeyField.js
#364 
I put my solution if it's relevant or the community agrees to add,the idea is to help the user who programs the device
Following the interface and to add may format to copy add a menu material with different options
a tooltip with description, and hide or show depend on the user
=> add copy clipboard for hex keys

packaging/scripts/post-install.sh
Just to align both packaging routines.
=> Add function as seen in chirpstack-network-server packaging

packaging/files/chirpstack-application-server.init, packaging/scripts/post-install.sh
=> Fix init script

docs/content/overview/changelog.md
=> Fixed typo

internal/config/config.go
Can be seen in brocaar/chirpstack-gateway-bridge/issues/163
=> Adding missing mapstructure in config.

internal/api/as/as.go
... to not rely on gateway time. Not sure about metrics timestamp and how it is used
Fixes #408
=> Fix gateway FirstSeenAt, LastSeenAt and metrics timestamp

internal/api/external/application_test.go, internal/api/helpers/errors.go, internal/storage/errors.go, internal/storage/service_profile.go
Fixes #425 
@brocaar Please review this
=> Fix create service-profile with empty name.

ui/src/views/gateways/GatewayDetails.js, ui/src/views/gateways/ListGateways.js
Also change "Last seen" to "Last seen at" on gateway detail page
Follows #386
=> Add "Last seen" columnt to gateway list view

internal/api/external/fuota_deployment.go
Details: https://github.com/brocaar/chirpstack-network-server/issues/475
=> Change ISM channel plan band to common name.

internal/api/helpers/errors.go, internal/storage/errors.go, internal/storage/multicast_group.go
=> Fix create multicast-group with empty name (blank string).

ui/src/views/api-keys/ListAdminAPIKeys.js, ui/src/views/applications/ListApplications.js, ui/src/views/applications/ListIntegrations.js, ui/src/views/device-profiles/ListDeviceProfiles.js, ui/src/views/devices/ListDevices.js, ui/src/views/fuota/ListFUOTADeploymentDevices.js, ui/src/views/fuota/ListFUOTADeploymentsForApplication.js, ui/src/views/fuota/ListFUOTADeploymentsForDevice.js, ui/src/views/gateway-profiles/ListGatewayProfiles.js, ui/src/views/gateways/ListGateways.js, ui/src/views/multicast-groups/ListMulticastGroupDevices.js, ui/src/views/multicast-groups/ListMulticastGroups.js, ui/src/views/network-servers/ListNetworkServers.js, ui/src/views/organizations/ListOrganizationUsers.js, ui/src/views/organizations/ListOrganizations.js, ui/src/views/search/Search.js, ui/src/views/service-profiles/ListServiceProfiles.js, ui/src/views/users/ListUsers.js
This commit enhnace user table interaction when viewing list items in ui.
Closes #471
Signed-off-by: Kiara Navarro <sophiekovalevsky@fedoraproject.org>
=> Add highlight row when user hover it at ui tables

internal/api/external/device_profile.go, internal/api/external/service_profile.go, internal/storage/device_profile.go, internal/storage/service_profile.go, ui/src/views/device-profiles/ListDeviceProfiles.js, ui/src/views/service-profiles/ListServiceProfiles.js
Details: https://github.com/brocaar/chirpstack-application-server/issues/470
=> Include Network Server Name column in Device and Service Profile List.

internal/integration/thingsboard/thingsboard.go
Details: https://github.com/brocaar/chirpstack-application-server/issues/477
=> Include RSSI and SNR in ThingsBoard.io

ui/src/views/gateways/GatewayDetails.js
Details: https://github.com/brocaar/chirpstack-application-server/issues/479
=> Theme Gateway Details Table

cmd/chirpstack-application-server/cmd/configfile.go, cmd/chirpstack-application-server/cmd/root.go, docker-compose.yml, docs/content/install/config.md, internal/config/config.go, internal/storage/storage.go, internal/test/test.go
related issue: https://github.com/brocaar/chirpstack-application-server/issues/490
@brocaar how do you feel about this implementation?
=> add redis servers for cluster

ui/src/App.js, ui/src/components/Loader.js, ui/src/stores/ApplicationStore.js, ui/src/stores/DeviceProfileStore.js, ui/src/stores/DeviceQueueStore.js, ui/src/stores/DeviceStore.js, ui/src/stores/FUOTADeploymentStore.js, ui/src/stores/GatewayProfileStore.js, ui/src/stores/GatewayStore.js, ui/src/stores/InternalStore.js, ui/src/stores/LoaderStore.js, ui/src/stores/MulticastGroupStore.js, ui/src/stores/NetworkServerStore.js, ui/src/stores/OrganizationStore.js, ui/src/stores/ServiceProfileStore.js, ui/src/stores/SessionStore.js, ui/src/stores/UserStore.js, ui/src/stores/helpers.js
Can be seen in https://github.com/brocaar/chirpstack-application-server/issues/492
=> Implement loader

internal/api/external/internal.go, internal/api/helpers/errors.go, internal/storage/errors.go, internal/storage/fuota_deployment.go, internal/storage/network_server.go, internal/storage/network_server_test.go
Resolved Network-server and FUOTA deployment create with an empty name (blank string)
@brocaar please review this Pull Request
=> API Bug: Fix create FUOTA deployment and Network-Server with empty name (blank string).

ui/src/views/applications/integrations/PilotThingsCard.js, ui/src/views/applications/integrations/ThingsboardCard.js
Drive-by: fix an English error in the ThingsBoard integration description
=> Update Pilot Things integration description

cmd/chirpstack-application-server/cmd/configfile.go, cmd/chirpstack-application-server/cmd/root.go, go.sum, internal/config/config.go, internal/integration/kafka/kafka.go
=> FEATURE: support SCRAM-SHA-256/512 for kafka integration

internal/api/external/user.go, internal/api/external/user_test.go
=> Users can't delete themselves from the user

ui/src/views/service-profiles/ListServiceProfiles.js
Fix https://github.com/brocaar/chirpstack-application-server/issues/588
=> Improve `ListServiceProfiles` add `ID` column

cmd/chirpstack-application-server/cmd/configfile.go
Update SQL Migration URL in config.go file
=> Update migrations URL.

ui/src/components/AESKeyField.js, ui/src/stores/helpers.js
=> Fix Copy key functionality

internal/storage/migrations/0060_dev_addr_to_global_search.down.sql, internal/storage/migrations/0060_dev_addr_to_global_search.up.sql, internal/storage/search.go
Fixes #601 
@brocaar Please review this change.
=> Add Device Address to search functionality.

.github/workflows/main.yml, Dockerfile
Signed-off-by: Krasi Georgiev <8903888+krasi-georgiev@users.noreply.github.com>
=> multi-arch github actions
