Makefile

A typo - came across this when looking into Docker files 'make serve' stanza

Fix lora-app-server path in Makefile

---

api/gen.sh

Allows GOPATH to be an actual path variable, and not just  a pointer to a directory.

Allow GOPATH to be an actual path

---

Dockerfile

A few setup commands were added to make the following tasks executable.
- `make requirements ui-requirements` and `make ui statics`
- `make package-deb`
- run lora-app-server on docker as following
`build/lora-app-server --jwt-secret=XXX  --http-tls-key=/etc/lora-app-server/certs/http-key.pem --http-tls-cert=/etc/lora-app-server/certs/http.pem`

Add setup commands to dockerfile

---

ui/src/views/gateways/GatewayToken.js

"to" is route , so the url like `<a href="#https://docs.loraserver.io/lora-gateway-config/overview/"> LoRa Gateway Config </a>`, have "#" is anchor.
So we need  modify "to"  to "href"

fix external site jump

---

cmd/lora-app-server/main.go

--gw-ping-dr defaults to 0 and 0 is now a valid value

 See issue #203 "common.GatewayPingDR == 0 should be a valid value"

---

ui/src/views/nodes/ListNodes.js

Fix following warning:
> Line 16:  Expected '!==' and instead saw '!='  eqeqeq

Fix a warning of eslint: eqeqeq rule

---

docs/content/use/devices.md

Provides some guidance on both Device Profile settings within LoraServer, and the changes to make to the stock Arduino LMIC code in order to get a node sending data.

Add the documentation for devices that use Arudino LMIC and OTAA

---

ui/src/views/multicast-groups/MulticastGroupForm.js

The FormHelperText associated with a selection box for choosing the Service Profile associated with the Multicast Group is referring to the Application instead of the Multicast Group. This is likely because it was a copy/paste of the FormHelperText of ApplicationForm.js

fix: Update MulticastGroupForm.js form helper

---

internal/api/as/as.go
internal/integration/models.go

Fixes brocaar/loraserver#235
Sorry it took me so long to get to this after I said I was looking at it. Other priorities got in the way until now.
Tests pass. I haven't actually tested this in production, but I can't see why it shouldn't work. I don't have a test environment set up here, only a production server that I can't replace with v3 quite yet.
I had to change `handleDeviceActivation` to take a `HandleUplinkDataRequest` rather than the `DeviceActivationContext` in order to get to the TXInfo and RXInfo and related fields. As far as I can see, it's only used in the one spot.

add RXinfo and TXinfo to JoinNotification

---

cmd/lora-app-server/cmd/configfile.go
docs/content/install/config.md
docs/content/integrate/api.md
docs/content/integrate/auth.md

I found an interesting word that I am not sure if it's a typo. If it's, then this pull request aims to fix it.

Fixing typo on api docs and config file.

---

ui/src/components/DataTable.js
ui/src/stores/SessionStore.js

Closes #351 
Persist rowsPerPage on DataTable in localStorage. Maintains the current default of 10 on login.
I wasn't sure if a nonexistent key returned an empty string or null (docs say null), so I tested for both, as you tested for the empty string in getOrganizationID. I've tested this myself and it seems to work fine.

persist rowsPerPage in localStorage

---

ui/src/components/DataTable.js

add option for 200 and 500 devices per page

Higher max rows per page on device list

---

internal/storage/organization.go

executing PUT request to below API for modify user details for the particular organization "UpdatedAt" field is not modified
/API/organizations/{organization_user.organization_id}/users/{organization_user.user_id}

API bug: Parameter "UpdatedAt" is not modified

---

docs/content/use/network-servers.md

Now rendered as raw markdown, see https://www.chirpstack.io/application-server/use/network-servers/

fix link in markdown to /network-servers/

---

internal/integration/awssns/aws_sns.go

Err was assigned but never checked, so probably an oversight.

add missing error check in aws sns integration

---

cmd/chirpstack-application-server/cmd/configfile.go
cmd/chirpstack-application-server/cmd/root.go
docker-compose.yml
docs/content/install/config.md
go.mod
go.sum
internal/config/config.go
internal/integration/integration.go
internal/integration/kafka/kafka.go
internal/integration/kafka/kafka_test.go
internal/test/test.go

using github.com/segmentio/kafka-go as kafka library.
including tests using bitnami/{kafka,zookeeper}.
similar to other integrations.
kafka broker(s) and topic can be configured.
message keys include application ID and dev EUI.

add kafka integration

---

Makefile

Hi,
I was suffering from the very slow build of chirpstack-application-server.
The reason was `go list ./...` at the second line of Makefile.
After `make ui-requirements`, the build time got slow seriously.
Especially, under the Windows and macOS that use VM based Docker environment, it got much slower than Linux.
So I fixed it not to list `ui` and its sub directories.
Please, review it.
Thank you.
Jongsoo Jeong

Fixed Makefile to speed up.

---

ui/src/components/AutocompleteSelect.js

- This is a bugfix for issue [#524](https://github.com/brocaar/chirpstack-application-server/issues/524)
Select controls were not displaying their placeholder value. To fix this a placeholder property has been added to `<TextField>` in the AutoCompleteSelect

Fix autocompleteselect placeholder

---

Dockerfile

It's a good practice to avoid running docker containers with root access
I currently have the app server deployed with a wrapping docker container performing the same
```dockerfile
FROM chirpstack/chirpstack-application-server:3.11.1
USER nobody:nogroup
ENTRYPOINT ["/usr/bin/chirpstack-application-server"]
```

Don't run as root

---

internal/integration/mqtt/mqtt.go

Fixes [#575](https://github.com/brocaar/chirpstack-application-server/issues/575) 
NOTE: the tests fail on docker-compose because of the issue with the latest mosquito image (see [issue](https://github.com/eclipse/mosquitto/issues/2040)) but pass fine if you specify mosquito version below 2.0.0 in docker-compose. I've been testing with version 1.6.12

The lock key for downstream messsages base on message content

---

internal/integration/postgresql/migrations/0002_devaddr_uplink_type.down.sql
internal/integration/postgresql/migrations/0002_devaddr_uplink_type.up.sql
internal/integration/postgresql/postgresql.go
internal/integration/postgresql/postgresql_test.go

Fixes #560 
@brocaar Please review my change.
Is it required to Store `RXINFO` in `JoinEvent`? if required then I will commit to this PR.

Store uplink is of type confirmed/unconfirmed + dev-addr in postgres integration.

---

ui/src/components/JSONTree.js
ui/src/views/devices/DeviceData.js

`gatewayID` also convert to base64ToHex in the lorawan frames tabs as it's already in HEX format. It was not shown properly due to `TxAck`  `gatewayID` base64ToHex conversion in JSONTree.js.
see attached screenshot for your reference.

Fix "gatewayID" hex converter in lorawan frames.

---

Dockerfile
Dockerfile-devel
internal/api/external/internal.go
internal/api/external/oidc/oidc.go

The OpenID Connect ("OIDC") login method currently attempts to fetch "claims" from the "id_token". However, it's optional for OIDC servers to put claims in that field. Certainly by default not all auth servers do that. You can request it with a "claims requested" field, but implementing that feature is optional for OIDC servers. Instead, the safer mechanism for fetching all claims seems to be a separate "userinfo" call. This change makes that call.
This change also passes the claims on to the registration callback url, as field "oidc_claims", in JSON. A separate provisioning tool can then use the claims to configure the user properly, eg assign them to an organization.
This change also makes sure that any changes to the user by the registration callback url are not overwritten when the …

Fetch OpenID Connect claims with UserInfo call, not id_token, and pass claims to registration callback url

---

cmd/chirpstack-application-server/cmd/configfile.go

And help user with an example for provider_url. It should prevent them from
making the mistake of adding the oidc well-known path.

Document the oidc_claims parameter for registration_callback_url in the config file

---

internal/integration/http/http.go

It's not recommended to use defaultClient in production, as it has no timeout at all. So if http-integration far-end application keeps holding all connections - it may lead to out of entire service. For instance when the number of connections reaches max open files, allowed by host-system (for example systemd allows 1024 max files by default). Custom timeout value can be implemented for each intergation configuration in future.

http-integrations: switched from default http.client to http client with timeout

---

internal/api/external/oidc/oidc.go
internal/api/external/oidc/oidc_test.go

@JaMurphSmi
> I have tried N different variations and been in contact with several support staff and raised a support ticket with Microsoft themselves to try and approach this issue, but it seems in the whole of Azure it is simply not possible in the current framework to pass a value as anything other than a string even if it’s defined as a Boolean.

FIX: email_verified is a string on azure instead of bool

---

go.mod
go.sum
internal/api/as/as_test.go
internal/events/uplink/uplink.go
internal/integration/marshaler/marshaler.go
internal/integration/marshaler/marshaler_test.go
internal/integration/models/models.go

This will close #611 and #609 
This also needs this pull request from chirpstack-api: https://github.com/brocaar/chirpstack-api/pull/47
As this pull request only adds two JSON fields it's **not** a breaking change

Extendes UplinkEvent with DeviceProfileName, DeviceProfileUUID and its Tags

---

go.mod
go.sum
internal/api/external/device.go
internal/backend/networkserver/mock/client.go
ui/src/stores/DeviceStore.js
ui/src/views/devices/DeviceActivation.js

Details:
- DevNonce clear functionality helps to remove older device
activation records from device_activation table in NS.
- Using this method we can clear older or already generated device activation
records from database to prevent "DevNonce already exits" error in OTAA method
*Note: Server keeps latest 20 records in device_activation table of NS database
for manage recent device activation.
Signed-off-by: SAGAR PATEL <sagar.a.patel@slscorp.com>

Add DevNonce Clear Functionality

---

cmd/chirpstack-application-server/cmd/configfile.go
cmd/chirpstack-application-server/cmd/root.go
internal/api/external/oidc/oidc.go
internal/config/config.go

use_userinfo is a configuration option which allows the user to configure
whether OIDC claims should be taken from the ID token (as per the OIDC
design) or whether a separate call should be made to the UserInfo endpoint
in order to take the claim from there. This works around issues with some
identity providers, and prior to this commit, the workaround was permamently
enabled. Set use_userinfo to true in order to preserve this behaviour.
assume_email_verified means that the email_verified claim will always be
assumed to be present and true, regardless of what the identity provider
sends. This is particularly useful for certain providers like Azure AD
which don't normally send the email_verified claim.
Fixes #619

Introduce use_userinfo and assume_email_verified options for OIDC

---

Dockerfile
Dockerfile-devel

Docker image golang:1.19.3-alpine has moved to nodejs version 18, this contains a breaking change causing the ui/build to fail.
Changed to golang:1.19.3-apline3.16 which still uses nodejs 16.

Fix alpine version to prevent nodejs bump
